spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 1122q!
    driver-class-name: org.h2.Driver
    platform: h2

app:
  jwtSecret: cdb7778b7ecf41ca88354f4b6cddc6c0cdb7778b7ecf41ca88354f4b6cddc6c0!
  jwtExpirationMs: 3600000
  timezone: America/Bogota