server:
  servlet:
    context-path: /api/v1
  port: 8001

spring:
  profiles:
    active: local
  application:
    name: ms-dvp-challenge
  cloud:
    kubernetes:
      secrets:
        enable-api: true
      discovery:
        all-namespaces: true

#Project info
app:
  version: @project.version@
  name: @project.name@
